#!/bin/bash

CLEAN=false

# Generic options
NOSU_VERSION=2.0.1
NOSU_PLATFORM=mellanox
NOSU_GIT_KERNEL="https://github.com/switchdev-nos/nosu-kernel"
NOSU_GIT_PACKAGES="https://github.com/switchdev-nos/nosu-packages"
NOSU_GIT_ROOTFS="https://github.com/switchdev-nos/nosu-rootfs"
NOSU_GIT_ONIE="https://github.com/switchdev-nos/nosu-onie"

# NOSU defaults
NOSU_TIMEZONE="Europe/Moscow"
NOSU_COMPRESS="xz"
NOSU_HOSTNAME=mellanox
NOSU_USERNAME=admin
NOSU_USERPASS=admin
NOSU_ROOTPASS=root

# DEB
DEBFULLNAME="Alexander Petrovskiy"
DEBEMAIL="alexpe@nvidia.com"

# NOSU KERNEL
NOSU_KERNEL_VERSION="5.12.12"
NOSU_KERNEL_LOCALVER="nosu"
NOSU_KERNEL_SNAPSHOT="https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/snapshot/linux-5.12.12.tar.gz"
#NOSU_KERNEL_GIT="https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
#NOSU_KERNEL_GIT_BRANCH="v5.12.12"
NOSU_KERNEL_PATCHDIR="patches"
NOSU_KERNEL_CONFIG="config/config-mlnx-default"

# NOSU PACKAGES
NOSU_PACKAGES=(
  frr
  bird
  iproute2
  ethtool
  ifupdown2
  keepalived
  mstpd
  vrf
  sosreport
)

# NOSU ROOTFS
NOSU_UBUNTU_BASE_URL="http://cdimage.ubuntu.com/ubuntu-base/releases/20.04/release/ubuntu-base-20.04.2-base-amd64.tar.gz"
NOSU_FWURL="https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/mellanox"
NOSU_FRRVER="frr-stable"
NOSU_TLABEL=NOSU
